//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadeDropDownListTrying.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        public System.Guid ID { get; set; }
        public System.Guid AppUserID { get; set; }
        public string CardOwnerName { get; set; }
        public string CardOwnerLastName { get; set; }
        public string CardNo { get; set; }
        public System.DateTime BestBeforeDate { get; set; }
        public string CardCVC { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedIP { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
